1
Shchekatya/stellar-burger pull request #6
Opened 2023-02-16 13:55 UTC by Shchekatya

2023-02-16 16:58 UTC, Shchekatya commented
У меня нет опыта работы с API. Попробовала захардкодить данные, но всё равно приходит ответ "Ingredient ids must be provided"

2023-02-16 17:35 UTC, andryxxa93 requested changes
Проделана большая работа! Вы хорошо разобрались `Context`. 

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- Добавьте проверку успешности запроса
- У всех элементов кроме булок должна быть иконка перемещения
- У верхней и нижней булки должны быть надписи "верх" и "низ".
- В консоли есть две ошибки связанные с key и неправильной типизацией.
<img width="1440" alt="Снимок экрана 2023-02-16 в 20 19 39" src="https://user-images.githubusercontent.com/60173362/219440111-98109809-ada7-4fa7-84e9-6ebfe10ec522.png">

- Добавить объект headers в запрос, тогда не будет ошибки. 
- Необходимо показывать пришедший ответом на post запрос номер заказа, а не захардкоженный. Если произошла ошибка, от модальное окно с номером заказа показывать не надо.
- Теперь данные необходимо передавать не через пропсы, а через контекст.
- Необходимо удалить файл `App.test.tsx` - он не нужен в проекте.

Более подробно описание проблемы смотрите комментарии в pull request.

Что понравилось:
- Правильно настроен Context.
- В Context обернуты только те компоненты, которые будут его использовать.
- Реализован механизм добавления в конструктор ингредиентов.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

Перед отправкой работы на проверку не забудьте проверить, что в консоли разработчика (F12) нет ошибок. 

Удачных правок!

2023-02-16 17:35 UTC, andryxxa93 commented on src/components/burger-constructor/BurgerConstructor.jsx
> +  const sendOrder=async (url = 'https://norma.nomoreparties.space/api/orders', data = {"ingredients": ["60d3b41abdacab0026a733c6","60d3b41abdacab0026a733ca"]}) => {
**Можно лучше**

в дальнейшем добавятся ещё запросы к бэкенду и лучше вынести описание этих запросов в функции

Например:

```
function getOrderNumber() {
   return fetch(`${NORMA_API}/orders`)
    .then(проверка ответа)
}

```

и разместить их в отдельном файле  `utils/burger-api.js`, а не описывать запросы в самом компоненте

2023-02-16 17:35 UTC, andryxxa93 commented on src/components/burger-constructor/BurgerConstructor.jsx
> +    let result = await response.json();
**Надо исправить**
Добавьте проверку ответа сервера - res.ok:

Например:

```
.then(res => res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
```

иначе сейчас, если сервер ответи не кодом 2xx, а какой либо ошибкой (4xx, 5xx) мы не попадем в catch т.к. в этом случае fetch не выбрасывает ошибку, мы попытаемся отрисовать данные, хотя они не пришли, в итоге на попытке отрисовки несуществующих данных упадет все приложение

[https://learn.javascript.ru/fetch](https://learn.javascript.ru/fetch)

[https://developer.mozilla.org/en-US/docs/Web/API/Response/ok](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok)

Т.к. эта проверка нужна у всех запросов, лучше вынести её в отдельную функцию

```
const checkReponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};
```

`fetch(someUrl).then(checkReponse)`

2023-02-16 17:35 UTC, andryxxa93 commented on src/components/ingredients/ingredients.jsx
> +//import { useContext } from "react";
**Можно улучшить**
Ненужный код лучше удалять

2023-02-16 17:35 UTC, andryxxa93 commented on src/components/burger-constructor/BurgerConstructor.jsx
> +      body: JSON.stringify(data),
**Необходимо исправить**
У вас ошибка из-за того что вы не указали объект `headers` с типом передаваемых данных. 
        headers: { 'Content-type': 'application/json' },

2023-02-16 17:35 UTC, andryxxa93 commented on src/components/burger-constructor/BurgerConstructor.jsx
> +console.log(props.orders.main)
**Можно улучшить**
Console.log нужен только для процесса разработки, перед сдачей проекта его нужно удалять, иначе она будет загружать консоль ненужной, а возможно и приватной информацией. А ошибку лучше записывать в state и показывать пользователю, чтобы он понимал, что происходит.

2023-02-16 21:37 UTC, Shchekatya commented
Спасибо за подробный разбор. Постаралась всё исправить. Но не знаю, что делать с ошибками в консоли. 
Выдает "Failed prop type: Invalid prop `orders.main` of type `array` supplied to `BurgerConstructor`, expected `object`", хотя я пописала, что main: PropTypes.array.
И "Each child in a list should have a unique "key" prop." , хотя я пописала компоненту key={order._id}
Подскажите, пожалуйста, как их победить

2023-02-17 17:23 UTC, andryxxa93 approved these changes
Отлично! Ваша работа принята, удачного продолжения обучения!

2023-02-17 17:23 UTC, andryxxa93 commented on src/components/burger-constructor/BurgerConstructor.jsx
> + (props.orders.bun &&
**Можно лучше**
Вот такие конструкции лучше помещать в `useEffect` чтобы не было лишних операций.

2023-02-17 17:23 UTC, andryxxa93 commented on src/components/burger-constructor/BurgerConstructor.jsx
> +  orders: PropTypes.objectOf(PropTypes.shape({
**Необходимо исправить**
Ошибка возникает из-за того что вы указали, что `orders` это объект содержаний другой объект.
Надо на самом деле так - 
`  orders: PropTypes.shape({
    bun: PropTypes.object,
    main: PropTypes.array,
  }).isRequired`

2023-03-04 12:12 UTC, merged